### ISSUE TITLE
Security alert when trying to open Lionel Henry's R-universe

### ISSUE THREAD

**Issue by maelle** [r-universe-org/help#127]
I.e. in Firefox for https://lionel-.r-universe.dev/  

I see an alert.

It seems the SSL certificate wildcard does not encompass the "lionel-" 

Pardon my French:

> Les sites web justifient leur identité par des certificats. Firefox ne fait pas confiance à ce site, car il utilise un certificat qui n’est pas valide pour lionel-.r-universe.dev. Le certificat est seulement valide pour les noms suivants : *.r-universe.dev, r-universe.dev
 
> Code d’erreur : SSL_ERROR_BAD_CERT_DOMAIN

**Comment by jeroen** [comment]
This seems ok: https://lionel-.github.io/

There must be a problem with the SSL cert...

**Comment by jeroen** [comment]
Oh you are right. OK so there is probably little I can do... perhaps this is some sort of fishing protection?

**Comment by maelle** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1184059

**Comment by maelle** [comment]
Not sure you want to have a fix for one user but could this R-universe be redirected to something? Something that would not clash with any other username.

**Comment by maelle** [comment]
For the record, as stated in the bugzilla thread from above, these days on GitHub a new username cannot start nor end with a hyphen.

![image](https://user-images.githubusercontent.com/8360597/154066280-5b907fa2-7238-404d-95b7-ef667838b89a.png)

**Comment by jeroen** [comment]
Thanks, that's a good find. I don't think we can do a redirect because firefox refuses to connect to the domain, so we can't even send a redirect. 

We could host a special page e.g. `lionel_.r-universe.dev` but then all the automatically generated links everywhere have to be fixed as well because `lionel-` turns op as a contributior in many packages...

**Comment by maelle** [comment]
I'm not sure the underscore is a good idea, it looks like it could be a problem too. :wink:

**Comment by jeroen** [comment]
I don't think there is much we can do about this. As said, the same problem appears for https://lionel-.github.io. It is a very unfortunate edge case for legacy github usernames, that is beyond our control. Hopefully @lionel- can find a way to fix a better username.
