### ISSUE TITLE
Universe for multiple organizations

### ISSUE THREAD

**Issue by maelle** [r-universe-org/help#130]
When setting up an universe for several organizations, what will ensure the commit status can be updated?

Is it as simple as installing the app for all organizations?

**Comment by maelle** [comment]
Relatedly, one should choose the organization that has the best name to be used as subdomain. :thinking:

**Comment by jeroen** [comment]
Yes. The app gives permission to set a commit-status. So wherever the app is installed, we can set the status.

**Comment by maelle** [comment]
> we only try to set a commit status if the package is in the same user/org as the registry

https://github.com/r-universe-org/find-changes/blob/master/action.yml#L66-L68
