### ISSUE TITLE
System Libraries

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/help#131]
I see this section of the metrics has been turned on. How is this actually populated?

`nanonext` (CRAN package) uses `libnng` and has 'system requirements' specified in DESCRIPTION.

But it doesn't feature in this list. It is quite a new package though, maybe it needs time to get added to some database.

**Comment by jeroen** [comment]
Thanks! The database is populated live, that should not be the issue.

This FAQ: https://github.com/r-universe-org/help#how-does-r-universe-analyze-system-dependencies-cc

So it looks like the package on r-universe was built locally using cmake instead of `libnng-dev`.

**Comment by jeroen** [comment]
I have added `libnng-dev` to our build image, and now it should show up on the results.

**Comment by shikokuchuo** [comment]
Thanks as always! Using system libs / building using cmake I'm fine either way. I just wondered if there was something else that I was supposed to do, but seems not.
