### ISSUE TITLE
The infinite scroll on the maintainers page doesn't work on my 4k monitor

### ISSUE THREAD

**Issue by yutannihilation** [r-universe-org/help#139]
I think you can just increase the number of cards initially loaded.

![image](https://user-images.githubusercontent.com/1978793/158039303-13807801-e110-4bf5-9c32-b5d77389d09a.png)

**Comment by yutannihilation** [comment]
Thanks for fixing!

**Comment by jeroen** [comment]
Thanks! Does it work now?

**Comment by yutannihilation** [comment]
Yes, confirmed it works now 👍
