### ISSUE TITLE
Organization not visible

### ISSUE THREAD

**Issue by SebKrantz** [r-universe-org/help#160]
Hi, thanks a lot for the really great work you are doing here! 

I recently set up a 'fastverse' universe at https://fastverse.r-universe.dev/ with in important set of high-performance packages by various authors. For this I created an organization account at https://github.com/fastverse and made a 'universe' repo on that account. So far everything works great, I am just wondering why this organization is not visible under https://r-universe.dev/organizations/ ? (I've done that a week ago, so I'd expect it to be there by now).

**Comment by jeroen** [comment]
I think it has to do with the fact that fastserve itself does not own any packages, it is only a registry with 3rd party packages. I think the system needs at least one package that is owned by an org, in order for it to show up in the list.

**Comment by jeroen** [comment]
I think if you move e.g. your fastverse package to the fastverse github org, it will probably start showing up...

**Comment by SebKrantz** [comment]
Ok, thanks, I've done that now. Let's see..

**Comment by jeroen** [comment]
You also need to update the url in your registry to trigger the new build: https://github.com/fastverse/universe
