### ISSUE TITLE
Add number of non remotes packages at the top of universe pages?

### ISSUE THREAD

**Issue by maelle** [r-universe-org/help#170]

**Comment by jeroen** [comment]
Where exactly? Basically this badge? https://r-lib.r-universe.dev/badges/:total

**Comment by maelle** [comment]
I was thinking 

![image](https://user-images.githubusercontent.com/8360597/171818233-eb818455-b3c2-4f69-b81e-accdd557f1f0.png)


Could be r-universe/ropensci (384 packages).

Does that number exclude remotes?

**Comment by mrustl** [comment]
>Does that number exclude remotes?

I can confirm that https://kwb-r.r-universe.dev/badges/:total exludes `remotes` for our KWB-R universe!

**Comment by maelle** [comment]
I see a number of packages on universes
