### ISSUE TITLE
Build fails due to GitHub actions timeouts after 1h 

### ISSUE THREAD

**Issue by mrustl** [r-universe-org/help#171]
Hi @jeroen,

I have two problems with the package I already had trouble with (#169).

First I can see `pkgmeta` two times: 

![grafik](https://user-images.githubusercontent.com/11964451/171821762-d7f72f48-1b5d-419a-8c79-dce203bdb0a4.png)

And second I cannot get the new build working on `r-universe` due to timeouts after 1h:
https://github.com/r-universe/kwb-r/runs/6720392194?check_suite_focus=true 

Also the remotes dependency for `pkgnet` is not corrected (I switched in the meanwhile to `uptake/pkgnet` -> https://github.com/KWB-R/pkgmeta/blob/7ca0e428e68d159b9379ef3caffaf7d0975ac6ab/DESCRIPTION#L56)

![grafik](https://user-images.githubusercontent.com/11964451/171822568-0063bfd5-eef2-4700-b056-3086b217daee.png)

Any ideas/suggestions how this can be fixed?

**Comment by mrustl** [comment]
Here the link to my working actions: https://github.com/KWB-R/pkgmeta/actions

**Comment by jeroen** [comment]
We have a limit of 1h on package builds... it looks like your vignette may be hanging? Maybe if the vignette takes very long or needs special setup, you can precompute the vignette: https://github.com/r-universe-org/help#how-to-publish-vignettesarticles-which-require-custom-softwaretokens-to-render

**Comment by mrustl** [comment]
Well the vignette uses behind the scenes `codemetar` and installs a lot of R packages which I do not want to do locally.... and creates a `codemetar.json`  (https://kwb-r.github.io/pkgmeta/codemetar.json).

Would it be possible that I add a code chunk to my vignettes so that `eval` will is set to `FALSE` only on your r-universe GH action machines, but not on ours?
