### ISSUE TITLE
r-universe not updating due to package size

### ISSUE THREAD

**Issue by dieghernan** [r-universe-org/help#175]
Hi @jeroen 

Our r-universe @ropenspain (https://github.com/r-universe/ropenspain) is not up-to-date. I checked the action:
https://github.com/r-universe/ropenspain/runs/6960653187?check_suite_focus=true and the error says:

```
File LAU2boundaries4spain_1.0.0.tar.gz is more than 100MB. This is currently not allowed.
``` 

I already removed that package from `packages.json` in https://github.com/rOpenSpain/universe/commit/12ffa3310758e19b43ae8a3f25fc8f8ad43e3a88 but it seems that this was not enough.

Could you please provide some feedback? Many thanks

Related: https://github.com/rOpenSpain/universe/issues/1

**Comment by jeroen** [comment]
Should be updated in no more than an hour.
