### ISSUE TITLE
Any possibility of increasing package limit? 

### ISSUE THREAD

**Issue by jpiaskowski** [r-universe-org/help#179]
I recently ran into this issue during an R-universe build: 

```
Error in sync::sync_from_registry("https://github.com/r-universe/idahoagstats") : 
  Personal universes are currently limited to 100 packages
```
[here is a link to the build error](https://github.com/r-universe/idahoagstats/runs/7079009330?check_suite_focus=true)

Any chance of changing this? I'm at ~125 for an organization account.

**Comment by jpiaskowski** [comment]
There were loads of packages in this that appear to have no presence on Github or Gitlab aside from the CRAN site. There may be presence on R-forge, but I have no way to specify that in R-universe. 

Thanks for this project, tho. It's really amazing.

**Comment by jpiaskowski** [comment]
I updated the universe to exclude github.com/cran packages, so it's under the limit now (at 98!)

**Comment by jeroen** [comment]
There are also 2 packages that seem broken (they show a red "build failure" on https://idahoagstats.r-universe.dev/ui#builds) so you could consider removing those as well.

For now we'll limit to 100 packages per user because we have thousands of users and are a bit tight on build cycles.
