### ISSUE TITLE
r-universe and Java 17

### ISSUE THREAD

**Issue by AQLT** [r-universe-org/help#185]
Hello,
I was wondering why R-universe uses Java 11 and not the last LTS release Java 17. Indeed, since October 2021 all the CRAN packages have to be compatible with this Java version and newer developments in Java (and so R packages that depend on it) might not be compatible with older Java version (this is for example the case of several R package that I’m working on). I think all the packages in R-Universe that depend on Java are also compatible with Java 17: they are either on CRAN or do not specify any restriction on the Java version in the description. The only exception I've seen is `tabulizer`, that has been removed fromCRAN for that reason, but a PR has been made 4 months ago to fix this compatibility problem.
So I was wondering if there was any plan to update the Java version used in r-universe or to enable the user to change it?
Thanks

**Comment by jeroen** [comment]
Which platform specifically do you mean? On Windows and Linux we use the stock Java I think? On MacOS indeed I think we set it to JDK 11 here: https://github.com/r-universe-org/build-and-check/blob/32d148d090b2c24a76b2ffde1b983abcf49db700/action.yml#L50

We could bump it I suppose, if that fixes more packages than it breaks. Can you link any examples from packages that don't work right now?

**Comment by jeroen** [comment]
On Linux we use a custom build image, that runs ubuntu jammy (22.04) and the `default-jre` package. Looks like this is indeed JDK11 now: https://packages.ubuntu.com/jammy/amd64/default-jre

**Comment by jeroen** [comment]
I think given that `default-jre` on Linux is Java 11, and Java 17 actually breaks quite a few things it is beter for now if we stick with Java 11 in our builds. CRAN also uses default-jdk in their Debian check servers.

I see Debian is currently experimenting with bumping `default-jdk` to Java 17, but that is still WIP: https://packages.debian.org/experimental/default-jdk

I would recommend package authors not to assume Java 17, as most linux systems will run JDK 11. But we can revisit this when more packages require Java 17.
