### ISSUE TITLE
Problem with sync

### ISSUE THREAD

**Issue by TuQmano** [r-universe-org/help#188]
(I just realized this was the place to post an issue, and not in the [r-universe/dnme-minturdep](https://github.com/r-universe/dnme-minturdep/issues/1) repo. Sorry 4 that! @jeroen  . Copy  / Paste it down here)

---

I follow instructions to set up this r-universe but I misspelled de` .json` filename. I originally called it **`package.json`** instead of **`packages.json`**. 

https://jeroen.github.io/runiverse2021/#47

I think that´s why the [GHA failed ](https://github.com/r-universe/dnme-minturdep/runs/7657003590?check_suite_focus=true#step:3:34)

![image](https://user-images.githubusercontent.com/12114624/182862237-b2dcddcd-b720-4f92-b568-c4ce9b5c6ff1.png)

Then I tried two things: 

1. I commit a new file with the correct name. Nothing happened for at least 4 hours (I understood the bot re-run process each hour or so). 

2. Then I tried to redo the whole process: 

- Delete the old repo
- Uninstall r-universe from the Github account
- Start from scratch

I can´t see any change from yesterday in the sync. I assume this repo is linked to my old repo workflow thought

Can I do something to re-start the whole process and get a correct installation @jeroen ?

**Comment by jeroen** [comment]
Thanks for the report, going to look into it

**Comment by jeroen** [comment]
Where is your `packages.json`? It is supposed to be in: https://github.com/dnme-minturdep/universe

**Comment by TuQmano** [comment]
Hi @jeroen , thanks for your answer. I see the .json file right there (in this commit https://github.com/dnme-minturdep/universe/commit/845aa9a4765c7df3682bf4493d761c8773e75cc0)

What I just realized after reading you and writing the previous line was that the repo was in _Private_ status. Just changed it. Hope this fix my problem. Thanks again!

![image](https://user-images.githubusercontent.com/12114624/184137279-b6a5162e-781e-489c-80b6-490786a23b57.png)

**Comment by jeroen** [comment]
Your packages.json file has invalid syntax (see the new log file)

**Comment by TuQmano** [comment]
Thanks a lot! Just fixed it https://github.com/dnme-minturdep/universe/commit/87eabad2744c5c31e9962a1b5ed82a5ae812c859
