### ISSUE TITLE
Source package build failure - generate package metadata

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/help#191]
This is new within the past month or so. For my last 2 commits, the source package build has failed (binaries generated fine).

See: https://github.com/r-universe/shikokuchuo/runs/7919503767?check_suite_focus=true

The issue seems to be at the Generate Package Metadata step:

```
  Error in names(datasets) <- c("name", "title") : 
    'names' attribute [2] must be the same length as the vector [1]
```

Changes in the package codebase have been minimal, so I can only assume it is because you are trying to extract more metadata now.

The package has 3 non-exported data objects starting with a `.` as well as an exported dataset.

Hope the above helps. Let me know if you need more info. Thanks.

**Comment by jeroen** [comment]
Thank for your report, should be fixed now.
