### ISSUE TITLE
mismatch in CRAN badge link

### ISSUE THREAD

**Issue by zkamvar** [r-universe-org/help#192]
I just released [ropensci/tinkr](https://github.com/ropensci/tinkr) to CRAN, but the Universe is complaining that there is no link back to the GitHub repo in the DESCRIPTION even though, [the link back to GitHub URL does exist](https://github.com/ropensci/tinkr/blob/a577e9b4f3b94bcf09ead5c77ed49373a31db5d6/DESCRIPTION#L37).

**Comment by jeroen** [comment]
Yes the cran status is checked once per day. Should fix itself
automatically.

Op ma 22 aug. 2022 18:41 schreef Zhian N. Kamvar ***@***.***>:

**Comment by jeroen** [comment]
The link should be fixed now. Lmk if there is still a problem! Thanks
