### ISSUE TITLE
Can't find cargo on macOS builder

### ISSUE THREAD

**Issue by eitsupi** [r-universe-org/help#208]
Thank you for maintaining R-universe.

I recently registered a package containing Rust code in my universe and noticed that the cargo command was missing on the macOS builder.
I was wondering if this is intentional, since it appears that cargo is available on Linux and Windows.
https://github.com/r-universe/eitsupi/actions/runs/3314809532/jobs/5482550549#step:9:50

**Comment by jeroen** [comment]
According to GitHub it should be there:

 - https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
 - https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

Maybe it is just not on the PATH?

**Comment by eitsupi** [comment]
Thank you for your immediate reply.
I checked the gifski logs and it looks like it is using this part to install rust.
https://github.com/r-rust/gifski/blob/68911d927fb34c43dede24ce1baab73346e8bf04/configure#L25

**Comment by jeroen** [comment]
Yeah that is true, but if rust is preinstalled it should use that. Hmm I'll have a look

**Comment by eitsupi** [comment]
Could it have been deleted when Homebrew was removed?

**Comment by jeroen** [comment]
Maybe, though rustc and cargo are their own installer, they are normally not part of homebrew.

**Comment by jeroen** [comment]
Hmm that didn't help...

**Comment by eitsupi** [comment]
It woks now, thanks!
