### ISSUE TITLE
Install GNU targets of Rust toolchain?

### ISSUE THREAD

**Issue by yutannihilation** [r-universe-org/help#219]
I'm surprised that this is accepted by CRAN. In my understanding, `rustup target add` should modify `~/.cargo`, which is not allowed by the CRAN repository policy. The reason why I guess this didn't get the CRAN maintainers angry is probably the targets are already installed (not confirmed yet). So, maybe R-universe can follow the setup?

hellorust's Makevars.win:
https://github.com/cran/hellorust/blob/f13573edd9600d4ae6d0760fca3826f53ddd9657/src/Makevars.win#L16-L17

**Comment by jeroen** [comment]
The CRAN toolchains default to gnu mingw toolchains so that line does not change any settings, it only prints a confirmation that the compiler is available.

The rule is there to support non-cran hosts, in particular CI provides such as github-actions, that do have rust/cargo installed but default to MSVC.

**Comment by yutannihilation** [comment]
Thanks.

> If we would know if a good way to test if a package needs rust, we could perhaps automatically install the toolchain on r-universe for those packages.

I'm sure it's good enough to check if `DESCRIPTION` has `cargo` for `SystemRequirements`. But, okay, I get your point. I thought R-universe's setup is the same as CRAN, which is kept secret, and hellorust's target is only CRAN and R-universe. To make it work generally, executing `rustup` might be fair.

**Comment by yutannihilation** [comment]
Ah, I see. The problem seems more complex than I expected. To avoid the fragility, you can choose to always install the targets, but it would be too expensive considering there are only several Rust packages on CRAN.

**Comment by jeroen** [comment]
I made a pull request to the GHA image to preinstall the target: https://github.com/actions/runner-images/pull/6661

**Comment by yutannihilation** [comment]
Yay, it got merged! Thanks so much.

**Comment by eitsupi** [comment]
Does it seem to be failing to build despite that runner's update was released? cc @paithiov909
https://github.com/r-universe/paithiov909/actions/runs/3685270724/jobs/6236133928#step:9:58

**Comment by jeroen** [comment]
I just tested this with hellorust, and it seems to work: https://github.com/r-rust/hellorust/commit/822c1681cecbcb8b2f2e10c343b37f7cce3ab057

I did notice you use a target `stable-x86_64-pc-windows-gnu` and we use `x86_64-pc-windows-gnu` so perhaps that matters?

**Comment by yutannihilation** [comment]
As discussed on [another place](https://github.com/extendr/rextendr/issues/216#issuecomment-1336362624), extendr uses GNU toolchain, not the default MSVC toolchain, on Windows with R >= 4.2. So, this difference might matter.

Note that, on R 4.1, R tries to build the 32-bit version, so you need to install `i686-pc-windows-gnu` target (I personally recommend dropping the support for R 4.1.).

**Comment by eitsupi** [comment]
FYI, I had to add the following line, which is slightly different from `hellorust`, to get a successful build of a package that uses `extendr` on GitHub Actions in eitsupi/prqlr#5

```makefile
rustup:
	rustup toolchain install stable-gnu || true
```

I don't know what this little difference in names indicates to me...

**Comment by jeroen** [comment]
I think if you just remove the `+$(TOOLCHAIN)` from your `Makevars.win` and only specify `target=x86_64-pc-windows-gnu` then it should work with the preinstalled rust on GitHub acitons?

**Comment by eitsupi** [comment]
> I think if you just remove the `+$(TOOLCHAIN)` from your `Makevars.win` and only specify `target=x86_64-pc-windows-gnu` then it should work with the preinstalled rust on GitHub acitons?

Thank you for your suggestion.
I tryed in eitsupi/prqlr#22, but it seems failed.

```log
export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER="x86_64-w64-mingw32.static.posix-gcc.exe" && \
	export LIBRARY_PATH="${LIBRARY_PATH};/c/Users/runneradmin/AppData/Local/Temp/Rtmpa48C69/Rbuild19a0517655c1/prqlr/src/./rust/target/libgcc_mock" && \
	cargo build target=x86_64-pc-windows-gnu --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
error: Found argument 'target=x86_64-pc-windows-gnu' which wasn't expected, or isn't valid in this context
```

**Comment by yutannihilation** [comment]
Thanks so much for exploring! I think extendr can switch back to the MSVC toolchain.

**Comment by jeroen** [comment]
@yutannihilation I think that is a good idea. To be more specific: we should just use the _default_ toolchain that is available (i.e. not specify any `+...` parameter) and only specify the `--target`, because that is what really matters.

**Comment by yutannihilation** [comment]
I want to agree with you, but the toolchain also matters (or mattered, at least). I think I'm not good enough to figure out what the things are and should be, but I'd like you to know we actually had several reasons to specify the toolchain; the other toolchain didn't worked for the 32-bit Windows, and the cross compilation has some limitation (e.g. doc tests are not executed).

**Comment by eitsupi** [comment]
Sorry to continue this thread again, but after switching toolchain, Windows builds of `prqlr` on R-universe now fail.
Normal GitHub Actions are fine, so I am wondering where the difference is.

> error: linking with `link.exe` failed: exit code: 1

https://github.com/r-universe/eitsupi/actions/runs/3741799364/jobs/6361839313#step:9:161

**Comment by yutannihilation** [comment]
Curious. I don't see such a problem on my package.

https://github.com/r-universe/yutannihilation/actions/runs/3720180814/jobs/6309514049

**Comment by yutannihilation** [comment]
These look the same error, but I couldn't find what's the cause.

- https://stackoverflow.com/questions/62417036/usr-bin-link-missing-operand-after-377-376-when-compiling-bitflags
- https://github.com/dtolnay/syn/issues/768
