### ISSUE TITLE
cryptic error when building html reference manual

### ISSUE THREAD

**Issue by jonathon-love** [r-universe-org/help#220]
hi,

i get the following error:

```
Rendering HTML reference manual for package: jmv
                           jmv 
  "outputs/jmv/extra/jmv.html" 
  Error in data.frame(page = paste0(names(db), ".html"), title = titles) : 
    arguments imply differing number of rows: 1, 0
  Calls: <Anonymous> -> get_help_metadata -> data.frame
  Execution halted
```

i assume there's a problem with my package, however the error message currently doesn't clarify things.

https://github.com/r-universe/jamovi/actions/runs/3587800418/jobs/6042145135#step:3:1103

with thanks

**Comment by jeroen** [comment]
Thanks! We recently started indexing the content of all of the help files, but it seems there was bug for packages without any help files.

**Comment by jeroen** [comment]
Btw, is there any reason the package doesn't have any manuals? Is there a pre-step required to generate them?

**Comment by jonathon-love** [comment]
> Is there a pre-step required to generate them?

yeah, exactly.

**Comment by jeroen** [comment]
@jonathon-love you can add a `.prepare` script to your repo, which includes the steps needed to build from a checkout. Our build system will automatically run this shell script after checkout running `R CMD build`.

**Comment by jonathon-love** [comment]
great to know. thanks.

**Comment by jonathon-love** [comment]
is there any docs on the `.prepare` script anywhere? (had a quick look, but couldn't find anything). something like this?

```
R -e "\
    install.packages('remotes'); \
    remotes::install_remote('https://cran.r-project.org/src/contrib/Archive/roxygen2/roxygen2_6.1.1.tar.gz'); \
    roxygen2::roxygenise(); \
"
```

with thanks
