### ISSUE TITLE
Rust version of Linux builder seems older than CRAN builders

### ISSUE THREAD

**Issue by eitsupi** [r-universe-org/help#227]
In the process of submitting prqlr to CRAN, I ran into the 'Minimum Supported Rust Version' issue (eitsupi/prqlr#37, PRQL/prql#1561).

The Linux builders in CRAN and R-universe all seem to use the distribution standard Rust, with the difference that the minimum Rust version in CRAN is Debian testing, while in R-universe it is Ubuntu LTS.
https://github.com/r-universe-org/base-image/blob/1b7e197353497469aaaf77e51ce3339ff83fd73d/Dockerfile#L15

Checking the Debian testing history, it appears that they are using a version that is approximately 4 months behind the Rust release.[^1]
Ubuntu LTS appears to be later than that.[^2]

[^1]: <https://tracker.debian.org/pkg/rustc>
[^2]: <https://packages.ubuntu.com/jammy/rustc>

This would indicate that packages that can be released in CRAN may not be released in R-universe.
So, is it possible to change the installation method of cargo to follow Debian testing?
Of course, it is not necessary that they match exactly, but it seems that the versions may be about 3 apart and this seems like a big difference.

**Comment by jeroen** [comment]
I will try to add a more recent rust to the ubuntu image. But I would still recommend trying to make your code portable: https://github.com/r-rust/faq#which-cargo--rustc-version-to-target

**Comment by jeroen** [comment]
The build image should now have the latest version from [ubuntu-mozilla-security/rust-next](https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/rust-next?field.series_filter=jammy). Can you test if this solves your issues?

**Comment by eitsupi** [comment]
Thank you for your quick support.
As you point out, this is definitely a headache for Linux users who do source installations.
Maybe this problem also occurs in RSPM...

prqlr is currently able to build with Rust 1.61, so I am not experiencing any problems, but at the tradeoff of installing the Rust package from GitHub (my fork) instead of from crates.io.
I feel that it is a difficult question as to which should be prioritized, support for old Rust or official installation from crates.io...

**Comment by jeroen** [comment]
In the gifski package I faced a similar problem, and I created it such that it checks the version of rust and uses an older cargo.toml on older versions of rust: https://github.com/r-rust/gifski/blob/master/configure

**Comment by eitsupi** [comment]
> In the gifski package I faced a similar problem, and I created it such that it checks the version of rust and uses an older cargo.toml on older versions of rust: [r-rust/gifski@`master`/configure](https://github.com/r-rust/gifski/blob/master/configure?rgh-link-date=2023-01-22T14%3A19%3A27Z)

Thanks again, that seems super useful!
