### ISSUE TITLE
Count badge for across universes

### ISSUE THREAD

**Issue by llrs** [r-universe-org/help#229]
As I commented in slack:

r-universe total badges only counts packages in the user universe. So if a user has more packages in other universes they are not added up. (for example https://hadley.r-universe.dev/badges)  Is there a way for it to show all the packages in the r-universe ?

This might be related/affected by #228

**Comment by jeroen** [comment]
Should be fixed now.

**Comment by llrs** [comment]
Nice, many thanks!
