### ISSUE TITLE
Fortran configuration on macOS R-release

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#254]
My OneSampleMR package depends upon the gmm package which requires gfortan.

On macOS if you try to load the gmm package but Fortran isn't installed or in the correct location the package won't run. This leads to failed examples in my r-universe build such as this one (which don't fail on CRAN)

<https://github.com/r-universe/remlapmot/actions/runs/5105299651/jobs/9270554064>

The error message is
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/runner/work/_temp/Library/gmm/libs/gmm.so':
  dlopen(/Users/runner/work/_temp/Library/gmm/libs/gmm.so, 6): Library not loaded: /opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0/libgomp.1.dylib
  Referenced from: /Users/runner/work/_temp/Library/gmm/libs/gmm.so
  Reason: image not found
Calls: msmm ... msmm_gmm -> loadNamespace -> library.dynam -> dyn.load
```

Interestingly, the build and check for R-oldrel on macOS succeeds, e.g.,
<https://github.com/r-universe/remlapmot/actions/runs/5105299651/jobs/9270554236>
so I am wondering whether there is some difference between the way Fortran is configured on R-release and R-oldrel for macOS?

I guess I could guard all the examples in my package which use gmm (with say `require("gmm")`) but it feels to me like gmm should be able to find the .so file it needs.

**Comment by jeroen** [comment]
This is a bug on the gmm package. Lets move the discussion to here: https://github.com/pchausse/gmm/pull/1

**Comment by remlapmot** [comment]
Thanks very much
