### ISSUE TITLE
Support for rustc 1.70 and/or control of rust toolchain?

### ISSUE THREAD

**Issue by tshauck** [r-universe-org/help#268]
Hi,

Thanks for providing this resource. I was hoping to publish a rust based R package however I'm running into challenges that a dependency of my rust package clashes with the installed rustc on the builder, so I'm getting:

```
error: package `half v2.3.1` cannot be built because it requires rustc 1.70, while the currently active rustc version is 1.65.0
```

half is used by the arrow rust package.

I think there are workarounds, but the selfishly the easiest would be to have the ability to use 1.70, either installed on the builder or the ability to manage w/ rustup.

If there's a different solution you'd recommend, I'd certainly be open to that too. Thanks!

[Failed build for context](https://github.com/r-universe/wheretrue/actions/runs/5476427996/jobs/9973967693)

**Comment by jeroen** [comment]
Hmm we use the [ppa from mozilla](https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/rust-updates/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy) which again I think is mostly ported from [the latest rust on debian](https://packages.debian.org/sid/rustc) which is currently 1.66.

Perhaps we should switch to the upstream `rustup` although I really wish rust crate authors would make some effort supporting the mainstream stable rust versions out there, instead of requiring a bleeding edge version...

**Comment by tshauck** [comment]
Ha, I certainly can sympathize with this after the last week of package updates. FWIW, I think it might cultural differences between the communities. E.g. `rustup` being from the [language team](https://github.com/rust-lang/rustup) and 1.70 being stable vs beta or the nightly build.

<img width="714" alt="image" src="https://github.com/r-universe-org/help/assets/421839/7d6e1de9-504a-4d7c-86ad-50772935175f">

If you'd be willing to try putting rustup on runners, I'd certainly be happy to help test.

**Comment by jeroen** [comment]
OK I'll try switching, see if this breaks other packages...
https://github.com/r-universe-org/base-image/pull/4

**Comment by tshauck** [comment]
Ok, thanks. I'll give it a look this afternoon (~5 hrs from now) and follow up.

**Comment by tshauck** [comment]
Looks like you may've seen this, but there looks to be an issue that the install process assumes cargo exists on the path, but it does not yet. I've updated the makevars file in my repo to run `rustup update` which at least locally and on non-r-universe action builds seems to run as expected. I'll check on the r-universe build next time it's triggered.

**Comment by jeroen** [comment]
There seems to be a problem because rustup installs in the user HOME dir, but github-actions overrides the user HOME with a path from the host.

**Comment by tshauck** [comment]
Yerp... seeing [90ec5dfc0882ecbc5c6091f4abd1f42b680aa9a3](https://github.com/r-universe-org/base-image/commit/90ec5dfc0882ecbc5c6091f4abd1f42b680aa9a3) 🤞... thanks for working on this

**Comment by jeroen** [comment]
OK this should be fixed. Now your package fails with another problem 😁  https://github.com/r-universe/wheretrue/actions/runs/5490134880/jobs/10007164366

**Comment by tshauck** [comment]
Onward -- thanks!

**Comment by jeroen** [comment]
Could you also associate your maintainer emaill address `thauck@wheretrue.com` with your github account? See https://github.com/r-universe-org/help#how-to-link-a-maintainer-email-addresses-to-a-username-on-r-universe

**Comment by eitsupi** [comment]
> half is used by the arrow rust package.

Since arrow-rs specifies 1.62 on the Cargo.toml, this may be better discussed in this issue apache/arrow-rs#181.
https://github.com/apache/arrow-rs/blob/aac3aa99398c4f4fe59c60d1839d3a8ab60d00f3/Cargo.toml#L76

**Comment by tshauck** [comment]
@jeroen I've associated the email.

![image](https://github.com/r-universe-org/help/assets/421839/2fa0a67c-df10-4a76-93e1-3c44f05b4fe0)
