### ISSUE TITLE
Badges - copy to clipboard Markdown code URLs seem to return 404 error codes for first three badges

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#280]
(A relatively minor query)

I notice that for the first 3 badges for a user or organisation that the URLs from the copy to clipboard Markdown code on the respective `badges` page, seem to return 404s.

To recreate this issue, go to say <https://ropensci.r-universe.dev/badges>

<img width="876" alt="Screenshot 2023-08-06 at 21 15 21" src="https://github.com/r-universe-org/help/assets/3777473/836da710-e92e-461a-8ceb-f672c47f0617">

and then click on the Markdown icon on the right handside for the first badge. The following Markdown code is copied to the clipboard
```md
[![:name status badge](https://ropensci.r-universe.dev/badges/:name)](https://ropensci.r-universe.dev/:name)
```
but the URL <https://ropensci.r-universe.dev/:name> returns a 404

![image](https://github.com/r-universe-org/help/assets/3777473/b0e08031-fd96-45b3-aa25-e063e129f206)

as do the URLs in the Markdown code for the second and third badges

* <https://ropensci.r-universe.dev/:registry>
* <https://ropensci.r-universe.dev/:total>.

I'm wondering if these 3 URLs in the Markdown code need modification?

**Comment by jeroen** [comment]
Thanks for caching this! I changed the markdown to link to the root domain now, for the meta-badges.
