### ISSUE TITLE
Suggestion: add examples how to add r-universe icon to common websites e.g. Hugo Academic Theme

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#283]
On my Hugo Academic theme website, adding the following to `content/authors/admin/_index.md`
```md
- icon: rocket
  icon_pack: fa
  link: https://remlapmot.r-universe.dev/
```
adds a rocket emoji to the set of icons as follows

![unnamed](https://github.com/r-universe-org/help/assets/3777473/1908a5ba-8df5-4c50-a36a-20f27e3c7a07)

Maybe this is worth documenting somewhere.

**Comment by jeroen** [comment]
Yeah, if we can document it concisely, I think the readme in the current repo could be a good place. Do you want to send a pr?

**Comment by remlapmot** [comment]
Have sent PR - please do edit as you like or request changes.
