### ISSUE TITLE
Can I specify an additional repository in which R-universe will look for dependencies?

### ISSUE THREAD

**Issue by etiennebacher** [r-universe-org/help#285]
Hi there!

One of my packages ([`tidypolars`](https://etiennebacher.r-universe.dev/tidypolars#)) has some build failures because I don't know how to specify the repos it should look into when downloading dependencies.

Basically, here's what happens:

* `tidypolars` depends on `polars`, which is not on CRAN
* `polars` has binaries available on R-universe. These binaries have different paths depending on the OS:
  * `https://rpolars.r-universe.dev` for Windows and macOS
  * `https://rpolars.r-universe.dev/bin/linux/jammy/4.3` for Ubuntu
* in `tidypolars` DESCRIPTION file, I don't put `polars` in the `Remotes` field because Github Actions would try to build from source while there are binaries available, so I simply specify the link above as an additional repo in `install.packages()` ([related lines in my workflow](https://github.com/etiennebacher/tidypolars/blob/44dc19d2f48a7f6e561e5ac606f6eaa0a296d170/.github/workflows/check.yml#L39-L47))

Problem: since `polars` is not in the `Remotes` field, the R-universe workflow tries to find it on CRAN and obviously [fails](https://github.com/r-universe/etiennebacher/actions/runs/5865468592/job/15902455283).

I think the easiest way to fix the builds for `tidypolars` on R-universe would be to enable `https://rpolars.r-universe.dev` (or its Ubuntu variant) when it is looking for dependencies. Is it possible to do so?

I guess that putting `polars` in `Remotes` would work as well but it would drastically increase the build time both on my workflows and R-universe workflows since it would need to compile `polars` from scratch.

Thank you!

**Comment by jeroen** [comment]
The easiest way is adding a copy of polars to your universe by adding it to
your packages.json. This way the binaries are automatically used when
building tidypolars.

Op di 15 aug. 2023 11:42 schreef Etienne Bacher ***@***.***>:

**Comment by etiennebacher** [comment]
Awesome, it works, thank you

**Comment by eitsupi** [comment]
Wondering if this can be reconsidered now that `config.json` (to specify CRAN version) has been added[^1].

[^1]: <https://github.com/r-universe-org/actions/commit/014e6cdd4cbd92765135142b28c191e059863d1b>

If there is a dependency on a package such as `arrow` that frequently fails to build binaries on CRAN, it seems that time and energy are wasted each time a source build is attempted[^2].
If we can specify other universes like R-multiverse community repo as additional repositories here, we can use binaries on the R-universe.

[^2]: Another approach would be to configure the binary library to download from the prescribed location when R-universe is detected, as I have added to `arrow` (apache/arrow#44476), but this may be difficult as it requires some modifications to the package.

**Comment by jeroen** [comment]
@eitsupi These days we support the `Additional_repositories` field in the package DESCRIPTION, does that help you? Or does it really need to apply to the entire universe?

I think having this information in the DESCRIPTION will make it more transparent to the end-user where the dependencies for this package are taken from.

**Comment by eitsupi** [comment]
Thanks for your reply.
Indeed, this is likely to be a problem on a per-package basis, so it may be better to use that field.

**Comment by jeroen** [comment]
OK great. I have not tested this feature much, can you let me know if it works well?

**Comment by eitsupi** [comment]
Unfortunately, CRAN seems to take precedence in the subsequent matrix build workflow.

## Build source pkg and vignettes

https://github.com/r-universe/eitsupi/actions/runs/13437346518/job/37542785564#step:4:128

```log
   trying URL 'https://community.r-multiverse.org/src/contrib/arrow_19.0.1.tar.gz'
  Content type 'application/gzip' length 4968119 bytes (4.7 MB)
```

## Build R-oldrel for MacOS x86_64

https://github.com/r-universe/eitsupi/actions/runs/13437346518/job/37544126139#step:5:246

```log
  trying URL 'https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/arrow_18.1.0.tgz'
  Content type 'application/x-gzip' length 130346925 bytes (124.3 MB)
```

---

Could this be a bug in R-multiverse as the following error is occurring?

https://github.com/r-universe/eitsupi/actions/runs/13437346518/job/37544125586#step:5:80

```log
   Warning: unable to access index for repository https://community.r-multiverse.org/bin/macosx/big-sur-arm64/contrib/4.4:
    cannot open URL 'https://community.r-multiverse.org/bin/macosx/big-sur-arm64/contrib/4.4/PACKAGES'
```

**Comment by jeroen** [comment]
I think `r-multiverse.org` is currently being migrated to another account so that may be unrelated. Maybe try again later.

> Unfortunately, CRAN seems to take precedence in the subsequent matrix build workflow.

Usually `install.packages()` will take the latest R version of each package it can find in any of the repos.

**Comment by eitsupi** [comment]
I see, thanks.
If there are no R-multiverse errors, it looks like it will work fine.

**Comment by eitsupi** [comment]
It looks fine now, thanks!
https://github.com/r-universe/eitsupi/actions/runs/13502795522/job/37726511304#step:5:292

```log
Install package dependencies
  Additional_repositories: https://community.r-multiverse.org/
  also installing the dependencies ‘colorspace’, ‘crayon’, ‘farver’, ‘labeling’, ‘munsell’, ‘RColorBrewer’, ‘viridisLite’, ‘generics’, ‘fs’, ‘pkgbuild’, ‘rprojroot’, ‘diffobj’, ‘utf8’, ‘assertthat’, ‘glue’, ‘purrr’, ‘R6’, ‘tidyselect’, ‘cpp11’, ‘bit’, ‘lifecycle’, ‘tzdb’, ‘gtable’, ‘isoband’, ‘scales’, ‘pkgconfig’, ‘dplyr’, ‘brio’, ‘callr’, ‘desc’, ‘digest’, ‘evaluate’, ‘magrittr’, ‘pkgload’, ‘praise’, ‘processx’, ‘ps’, ‘waldo’, ‘fansi’, ‘pillar’
  
  trying URL 'https://community.r-multiverse.org/bin/macosx/big-sur-arm64/contrib/4.3/arrow_19.0.1.tgz'
  Content type 'application/octet-stream' length 17460609 bytes (16.7 MB)
  ==================================================
  downloaded 16.7 MB
```
