### ISSUE TITLE
Failing builds due to API rate limit exceeded

### ISSUE THREAD

**Issue by JanMarvin** [r-universe-org/help#288]
Hi,

just to let you know: since yesterday (Aug 23) various r-universe builds are failing due to

```R
Error in `gh::gh()`:
  ! GitHub API error (403): API rate limit exceeded for user ID 44377715.
  ℹ Read more at
    <https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting>
  Backtrace:
      ▆
   1. └─buildtools::generate_metadata_files(...)
   2.   └─buildtools::get_gitstats(repo, pkgdir, git_url)
   3.     └─gh::gh(sprintf("/repos/%s", repo))
   4.       └─gh:::gh_make_request(req)
   5.         └─gh:::gh_error(resp, error_call = error_call)
   6.           └─cli::cli_abort(...)
   7.             └─rlang::abort(...)
  Execution halted
```

See e.g. [here](https://github.com/r-universe/janmarvin/actions/runs/5969339698/job/16195036423), but I've checked a few other packages too (github.com/r-universe and pick any of the newly updated repositories). Not sure if Github has decreased the rate limit or if something else is interfering (like CRAN rebuilds etc.).

**Comment by jeroen** [comment]
Thanks, I had noticed this too. Not sure what happened, I'll try with some other tokens.

**Comment by jeroen** [comment]
I think this is fixed now, but thanks for helping to keep an eye out!

**Comment by JanMarvin** [comment]
Thanks for the build infrastructure!
