### ISSUE TITLE
Issue with Windows only package

### ISSUE THREAD

**Issue by rickhelmus** [r-universe-org/help#292]
Hello,

Recently I started experimenting with r-universe. My plan is to add a few packages that normally need to be fetched from GitHub. One of these is[ a fork of RDCOMClient](https://github.com/BSchamberger/RDCOMClient). This package seems to need Windows header files to build, which currently [prevents it to work with r-universe](https://github.com/r-universe/rickhelmus/actions/runs/6214327398/job/16950365997) (because the source package is build on Linux?). Is there any workaround possible?

Thanks,
Rick

**Comment by jeroen** [comment]
I think for Windows-only packages you need to put `OS_type: windows` in the `DESCRIPTION` file.

**Comment by rickhelmus** [comment]
Hi Jeroen,

Thanks! That seems to fix the build indeed :-)

A minor nag: I noticed that the commit that changes the DESCRIPTION in [my r-universe GitHub page](https://github.com/r-universe/rickhelmus/commits/master) suggests that the original author made the change instead of me ;-)

Thanks,
Rick

**Comment by jeroen** [comment]
Yes we use the maintainer email address from the DESCRIPTION as the universe committer. So you should update that email address to your own, if you are maintaining this fork.
