### ISSUE TITLE
Lowercase issue with package name prevents sync

### ISSUE THREAD

**Issue by baptiste** [r-universe-org/help#293]
I mistakenly used lowercase for the github repository [nano-optics/RcppFaddeeva](https://github.com/nano-optics/RcppFaddeeva) in the past, and it's triggered all sorts of problems since. On r-universe, it seems to prevent sync, with this error message:

 > ERROR Package 'rcppfaddeeva' from registry does not match package name in description file: 'RcppFaddeeva' 

I'm not too sure what to do: I renamed the github repo with capitals, but I think the change is not being noticed (because some part of the toolchain is case-insensitive, I guess). I could delete the repo and create a new one, but that's a bit unfortunate as I'll lose the history.

**Comment by jeroen** [comment]
You need to also change the name here: [nano-optics](https://github.com/nano-optics/RcppFaddeeva)

**Comment by baptiste** [comment]
Sorry, I don't understand: the github repo has the capitalised name, but it seems that r-universe is still looking for the lowercase version (which I guess github automatically redirects), and doesn't like that it's mismatched?



<img width="1029" alt="Screen Shot 2023-10-05 at 7 30 02 PM" src="https://github.com/r-universe-org/help/assets/18970/1b0c0ef5-fb99-4f65-a548-38b2f80cc65e">
<img width="689" alt="Screen Shot 2023-10-05 at 7 30 40 PM" src="https://github.com/r-universe-org/help/assets/18970/fec6e632-3e37-4e4b-847f-6c5959fbd9ce">

**Comment by jeroen** [comment]
Sorry, i meant that you need to update the packages.json file in your
'universe' repo to reflect the new name.

Op do 5 okt. 2023 08:33 schreef baptiste ***@***.***>:

**Comment by baptiste** [comment]
Thanks - I didn't get it to work so I deleted the repo and started from scratch ¯\_(ツ)_/¯
