### ISSUE TITLE
Installing from commit hash

### ISSUE THREAD

**Issue by rickhelmus** [r-universe-org/help#294]
Hello,

According to #141 it should be possible to checkout from a given commit hash. However, [when trying this](https://github.com/rickhelmus/rickhelmus.r-universe.dev/blob/72bf9389ac3f7ff0c6c3018f342b0a6a54212e0d/packages.json#L35), I get [the following error](https://github.com/r-universe/rickhelmus/actions/runs/6419684659/job/17430051744#step:3:26)

```
Failed to get upstream status for https://github.com/cbroeckl/RAMClustR@e005614d808e0ca93c459ec8cc103b87cd5d11fd
```

Thanks,
Rick

**Comment by jeroen** [comment]
Thanks for reporting! Should be fixed now!

**Comment by rickhelmus** [comment]
Awesome, thanks!
