### ISSUE TITLE
`pkg-config` cannot find `fftw3` in WASM

### ISSUE THREAD

**Issue by dipterix** [r-universe-org/help#321]
Works on all other platforms except WASM
https://github.com/r-universe/rave-ieeg/actions/runs/6802860776/job/18584283355

configure.ac:
https://github.com/dipterix/ravetools/blob/master/configure.ac

**Comment by jeroen** [comment]
Yes this is expected. Currently only a few C/C++ libs have been ported to WASM. If you want to contribute, you can try sending a PR to here: https://github.com/r-wasm/webr/tree/main/libs/recipes
