### ISSUE TITLE
Disable WASM?

### ISSUE THREAD

**Issue by tshauck** [r-universe-org/help#323]
Hi,

I'm wondering if it's possible to disable WASM builds? I'm running into an issue in that the builds are failing with the WASM target with:

```
using C compiler: 'gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0'
rm -Rf exonr.so ./rust/target/release/libexonr.a entrypoint.o
gcc -I"/opt/R/4.3.0/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c entrypoint.c -o entrypoint.o
rustup update
/bin/bash: line 1: rustup: command not found
make: *** [Makevars:20: update] Error 127
ERROR: compilation failed for package 'exonr'
* removing '/tmp/Rtmpicy0e7/pkg-lib1c4fa6b309/exonr'
```

`/bin/bash: line 1: rustup: command not found` being the issue. The package (`exonr`) uses rust, but even if `rustup` was installed I don't think the package would build for WASM which is why I'm wondering about disabling it... here's a link to the build: https://github.com/r-universe/wheretrue/actions/runs/6835529850/job/18589521444. There are a few other build issues unrelated to WASM/Rust that I'm working through.

Thanks!

**Comment by jeroen** [comment]
Hi, thanks for your comment.

It is not possible to customise the build process for individual packages but you may just ignore the wasm build. WASM is very experimental and currently does not work for some packages with 3rd party system requirements, such as rust. But this should not affect your deployment in any way: https://wheretrue.r-universe.dev/exonr

**Comment by tshauck** [comment]
Ok, thanks.
