### ISSUE TITLE
Package missed when building multiple packages from a monorepo

### ISSUE THREAD

**Issue by richfitz** [r-universe-org/help#326]
We have a repo containing (currently) two related packages that we want to layout as:

```
DESCRIPTION <-- root containing the first package
drivers/
  windows/
    DESCRIPTION <-- a related package, within a sub-sub-directory
```

The real example is here https://github.com/mrc-ide/hermod and the r-universe json file is [here](https://github.com/mrc-ide/universe/blob/main/packages.json#L282-L291).

We see only the root package (hermod) and not the package in the subdirectory (hermod.windows). I _think_ I've got the url correct, but could not find docs confirming that it should be done that way. The builds don't mention the missing package: https://github.com/r-universe/mrc-ide/actions

Is this possible to do this? Do I just have the url incorrect, or is having two packages in one repo causing the issue?

**Comment by jeroen** [comment]
You can use the `subdir` value in the registry to point to a package within a subdir, some examples here: https://github.com/r-universe-org/cran-to-git/blob/HEAD/r-forge.json

Although arguably the url syntax is nicer, maybe we should support that too.

I think it should work (given that the two packages have a different name?)
