### ISSUE TITLE
Pdf manual fail to build with TinyTex: Unicode character not set up for use with LaTeX

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#336]
PDF manuals fail to build if a help page contains utf-8 characters for which it doesn't have a fond?

  - https://ropensci.r-universe.dev/piggyback/buildlog
  - http://rstudio.r-universe.dev/gt/buildlog

Is there a way for latex to just replace this with a tofu?

Piggyback fails with:

```
LaTeX errors:
! LaTeX Error: Unicode character ℹ (U+2139)
               not set up for use with LaTeX.
```

Which seems to be inserted by cli here

```r
#' @return Writes file to release and returns github API response
#' @examples \donttest{
#' \dontshow{if (interactive()) \{}
#'   pb_write(mtcars, "mtcars.rds", repo = "tanho63/piggyback-tests")
#'   #> ℹ Uploading to latest release: "v0.0.2".
#'   #> ℹ Uploading mtcars.rds ...
#'   #> |===============================================================| 100%
#' \dontshow{\}}
#'}
```

And `gt` fails with:

```
LaTeX errors:
! LaTeX Error: Unicode character ⁠ (U+2060)
               not set up for use with LaTeX.
```

In the case of `gt` it seems to be

```r
\if{html}{\out{<div class="sourceCode r">}}\preformatted{reactions |>
  dplyr::filter(cmpd_type == "nitrophenol") |>
  dplyr::select(cmpd_name, OH_k298, Cl_k298) |>
  dplyr::filter(!(is.na(OH_k298) & is.na(Cl_k298))) |>
  gt(rowname_col = "cmpd_name") |>
  tab_spanner(
    label = "Rate constant at 298 K, in \{\{cm^3 molecules^–1 s^–1⁠<0x2060>\}\}",
    columns = ends_with("k298")
  ) |>
```

Latex is such a headache. We have html manuals now, maybe let's just get rid of the pdf ones?

**Comment by roaldarbol** [comment]
Agree on this. The HTML documentation is a far better user experience anyways. 
(Landed here as I currently have source build failing solely because it cannot render the PDF due to LaTeX errors - for reference: https://github.com/r-universe/roaldarbol/actions/runs/7879432188/job/21499673403)

**Comment by jeroen** [comment]
The main problem seems UTF-8 characters. Piggyback fails with:

```
LaTeX errors:
! LaTeX Error: Unicode character ℹ (U+2139)
               not set up for use with LaTeX.
```

And `gt` fails with:

```
LaTeX errors:
! LaTeX Error: Unicode character ⁠ (U+2060)
               not set up for use with LaTeX.
```

**Comment by jeroen** [comment]
Looks like switching to `xelatex` engine solved this issue: https://github.com/r-universe-org/build-source/commit/57a521806c79ae112300aa680d039c813b8e75b1

However I have no idea what side effects this has on other manuals or vignettes.
