### ISSUE TITLE
Install aarch64-apple-darwin target of Rust toolchain for cross-compile

### ISSUE THREAD

**Issue by yutannihilation** [r-universe-org/help#340]
I saw this comment and tried to cross-compile my Rust-powered package for arm64 macOS.

https://github.com/r-universe-org/help/issues/97#issuecomment-1880221054

But, it currently fails because the R-universe's runner doesn't have `aarch64-apple-darwin` target installed.

https://github.com/r-universe/yutannihilation/actions/runs/7442778977/job/20246753858

```
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-darwin`
error[E0463]: can't find crate for `compiler_builtins`
error[E0463]: can't find crate for `core`
```

Is it possible to make the target available for builds that use Rust? Just like [the case of the GNU toolchain on Windows](https://github.com/r-universe-org/help/issues/219), we can probably run `rustup add` in `Makevars`, but it's nice if it's pre-installed.

**Comment by yutannihilation** [comment]
Oh, cool!!! Thanks so much.

> So seemingly this changes the entire toolchain, not just the target.

Yes, `rustup default` is a command to set the default toolchain, not target.

``` console
❯ rustup default -h    
rustup.exe-default 
Set the default toolchain
```

> Do you know if there is a way to tell rustup/cargo to target by default `aarch64-apple-darwin`?

It seems there are no handy way for target like `rustup default`, but it seems we can configure it by putting these lines into `$CARGO_HOME/config.toml` (I haven't tried it yet). As this is [the least priority of configuration](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure), this is less likely to accidentally overwrite users' configuration.

``` toml
[build]
target = "aarch64-apple-darwin"
```

c.f. https://stackoverflow.com/questions/49453571/how-can-i-set-default-build-target-for-cargo

Or, setting `CARGO_TARGET` envvar might also work.

c.f., https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables

I'm not sure if this affects the location of the artifact, which accordingly requires users to tweak `LIBDIR` (i.e. `./rust/target/release` vs `./rust/target/aarch64-apple-darwin/release`). I need to test.

**Comment by yutannihilation** [comment]
> I'm not sure if this affects the location of the artifact, which accordingly requires users to tweak `LIBDIR` (i.e. `./rust/target/release` vs `./rust/target/aarch64-apple-darwin/release`)

Hmm, it seems both ways cause this and there's no way to handle the change of the location of the artifact transparently. There are several proposals related to this (e.g. https://github.com/rust-lang/cargo/issues/6100, https://github.com/rust-lang/rfcs/pull/3371), but, at the moment, the package needs to be cross-compile-aware.

I doubt arm64 macOS runners become available soon, considering they have repeatedly delayed the roadmap (c.f. https://github.com/actions/runner-images/issues/2187). But, ultimately, the crosss-compile is a temporary workaround until it eventually comes. So, IMHO, it's fine to impose the effort to package authors at this stage.

**Comment by jeroen** [comment]
I found a hack to make it work I think. 

I added the following shim (wrapper) for cargo to the PATH on the macos cross environment: https://github.com/r-universe-org/prepare-macos/blob/master/shims/cargo.sh

The shim both overrides the default target and then copies the `aarch64-apple-darwin` to the parent dir afterwards.

**Comment by yutannihilation** [comment]
Looks good to me!
