### ISSUE TITLE
All builds currently failing

### ISSUE THREAD

**Issue by stevencarlislewalker** [r-universe-org/help#359]
This is probably already known, but in case it isn't.  The at the time of writing the current status of https://r-universe.dev/builds/ looks like this.

![image](https://github.com/r-universe-org/help/assets/2754158/44de9963-52dc-4194-891c-ada39b573dde)

[Here](https://github.com/r-universe/canmod/actions/runs/8003626290/job/21859910034) is an example of a failure.

**Comment by jeroen** [comment]
Thanks, it looks like there is a problem with posit's p3m. I'll ask their admin,

**Comment by stevencarlislewalker** [comment]
Thank you so much!  I love r-universe!

**Comment by stevencarlislewalker** [comment]
Fixed now.  Thank you, even if it just fixed itself.

**Comment by jeroen** [comment]
Hmm not sure if it is fixed or just intermittent. I'll try to retrigger the failed builds, see if all is stable now.

**Comment by jeroen** [comment]
OK they fixed it. FYI here is the p3m status page: https://status.posit.co/#past-incidents
