### ISSUE TITLE
Scheduled checks?

### ISSUE THREAD

**Issue by wlandau** [r-universe-org/help#368]
For https://github.com/r-releases, regularly scheduled `R CMD checks` and revdep checks would help assure that the package ecosystem is internally consistent and working properly. I believe CRAN runs them about every week, and I would like to enact something similar across the entirety of `r-releases`.

I know I already commented on this in https://github.com/r-universe-org/help/issues/364#issuecomment-1968207674, but I would still like to post this as its own issue thread.

**Comment by jeroen** [comment]
We already rebuild all packages for all platforms once per month. Doing everything every week is too expensive, but perhaps we can do something smarter, like rerun CMD check on Linux, or rebuild all packages who have a dependency that was updated.

**Comment by wlandau** [comment]
Oh cool, I didn't know we already have monthly rebuilds! (R CMD check always runs during that rebuild process, right?) This seems good enough to support an initial rollout of https://github.com/r-releases (whereas #362 will make more of an impact for that project).

I really like your idea of Conditional rebuild based on dependencies would help to

**Comment by wlandau** [comment]
Closing in favor of #369.
