### ISSUE TITLE
GitLab releases

### ISSUE THREAD

**Issue by wlandau** [r-universe-org/help#379]
Continuing from #378, it would be great if R-universe could support [GitLab releases](https://docs.gitlab.com/ee/user/project/releases/) so [R-releases](https://github.com/r-releases) could pull from repos other than GitHub.

You mentioned that `"branch": "*release"` is parsed directly by R-universe rather than `remotes`: https://github.com/r-universe-org/sync/blob/bc8d3051cdc7c3b48c5d6ad9a9584b2fdddd595d/R/monorepos.R#L592-L605.

It is possible to get the tag of the latest GitLab release using e.g. https://gitlab.com/api/v4/projects/wlandau%2Ftest/releases.

~~These API calls do need authorization, but presumably R-universe already takes care of this if it can currently get GitLab commits and tags.~~

Happy to help however else I can.

**Comment by wlandau** [comment]
By the way, if it's not a security issue to tell me, how does R-universe authenticate and manage credentials for GitLab? If possible, I would like to do this in the R-releases bot so GitLab contributions can automatically be merged (https://github.com/r-releases/r.releases.internals/blob/2c5d0518d79ba17a13031bc17bc302531a8297f6/R/assert_package.R#L112).

**Comment by wlandau** [comment]
NB GitLab appears to have an "upcoming release" feature and there is an `upcoming_release` field in the JSON to indicate whether a release is "upcoming" ro not.

**Comment by jeroen** [comment]
I don't think we do any auth to GitLab right now, and only use public services.

**Comment by jeroen** [comment]
We can easily add a PAT token to the environment if we turn out to run into API limits.

So the code to lookup the latest release is like this?


```r
df <- jsonlite::fromJSON("https://gitlab.com/api/v4/projects/wlandau%2Ftest/releases")
latest <- df[1,'tag_name']
```

Do you have any GitLab package in `r-releases` to test with?

**Comment by wlandau** [comment]
> So the code to lookup the latest release is like this?

That's what works for me for https://gitlab.com/wlandau/test.

> Do you have any GitLab package in r-releases to test with?

I just created https://gitlab.com/wlandau/test/-/releases/0.0.3 with a release of a stub of an R package. I will put this in its own small universe.

**Comment by wlandau** [comment]
https://github.com/wlandau-test/wlandau-test.r-universe.dev/blob/main/packages.json now includes https://gitlab.com/wlandau/test. If/when the GitLab API call works in R-universe, https://wlandau-test.r-universe.dev should pick up https://gitlab.com/wlandau/test/-/releases/0.0.3.

**Comment by jeroen** [comment]
I think it worked: https://github.com/r-universe/wlandau-test/commits/master/

**Comment by jeroen** [comment]
Cool. If you find we are getting rate limit errors we should probably get a PAT but for now it seems OK.

**Comment by wlandau** [comment]
Sounds good. The last thing I am wondering about is what to do with "upcoming" releases in GitLab and "pre-releases" in GitHub. Do you think it's worth filtering those out?

**Comment by jeroen** [comment]
I don't feel strongly about it either way. Maybe it makes sense to include them if this is a QA repo, because that is what we want to be testing against?

**Comment by wlandau** [comment]
I was hoping R-releases would be "production" in the sense that the maintainer is confident in the release in isolation, but QA in the sense that users might need non-default tools to make sure packages aren't hitting problems after release.

**Comment by wlandau** [comment]
Our goal is to be able to layer production systems on top of it, and it seems hard if that were to include pre-releases.

**Comment by jeroen** [comment]
OK so you prefer to filter them?

**Comment by wlandau** [comment]
Yes, on reflection I definitely would, for both GitHub and GitLab if feasible. For GitHub, there is a `prerelease` field in the JSON response. For GitLab, it's called `upcoming_release`.

**Comment by jeroen** [comment]
OK updated here: https://github.com/r-universe-org/sync/commit/54798bf69a3f39e561be95640fa9f7062d62b18a

**Comment by wlandau** [comment]
Thanks, I think GitLab is covered now. Would it be okay to do the same with the `prerelease`  field for GitHub repos?

**Comment by wlandau** [comment]
Ah, so the release won't be "latest" if it is a pre-release? And `"branch": "*release"` will never pull a pre-release?

**Comment by jeroen** [comment]
Yes that is correct, it is impossible on GitHub to mark a pre-release as the "latest" release.
<img width="537" alt="Screenshot 2024-03-07 at 20 22 27" src="https://github.com/r-universe-org/help/assets/216319/aed8a783-0f0b-4cbc-bbf1-e2d48ec9e7ab">

**Comment by wlandau** [comment]
Perfect!
