### ISSUE TITLE
Builds breaking with function-not-found `guess_development_url`

### ISSUE THREAD

**Issue by coolbutuseless** [r-universe-org/help#389]
Build process seems to be broken.

Happening in multiple repos e.g.

* https://github.com/r-universe/moosa-r/actions/runs/8486643911/job/23253340739
* https://github.com/r-universe/tylermorganwall/actions/runs/8486514003/job/23253026334
* https://github.com/r-universe/coolbutuseless/actions/runs/8481080735/job/23237856266

```
  Error in guess_development_url(package, tolower(git_url)) : 
    could not find function "guess_development_url"
```

**Comment by jeroen** [comment]
Oops, bad deploy, sorry.

**Comment by jeroen** [comment]
Should be fixed now, clearing the backlog....
