### ISSUE TITLE
failed builds require new package version to update package source

### ISSUE THREAD

**Issue by JosiahParry** [r-universe-org/help#392]
I'm trying to get a new build of my package working on r-universe. however the package build has failed (which is totally fine). I've pushed a change to the makevars to fix it and pressed the retry build button. However, this appears to use the cached source from the previous failed build. It requires a new package version in order for a the source to be updated. 

Is there a way for this caching of package source to not happen for failed package builds? So that a package does not need to have its version incremented for a bad build?

**Comment by jeroen** [comment]
The package will automatically get updated every hour.

**Comment by jeroen** [comment]
Did your problem get fixed? Can you please close the issue if it did.

**Comment by JosiahParry** [comment]
No, it didnt but it sounds like its as designed.

**Comment by jeroen** [comment]
So can you link to the failing build please?

Op vr 5 apr. 2024 16:53 schreef Josiah Parry ***@***.***>:

**Comment by JosiahParry** [comment]
My apologies for not getting back to you. This is the build I was trying to debug https://github.com/r-universe/josiahparry/actions/runs/8555402708/job/23512987135. 

The build works locally with the webR docker image and the patched crates.io path but not using the r-universe builder.

**Comment by JosiahParry** [comment]
I'm running into frustrations with this again. I think I understand what is bothering me. Its not necessarily that I have to wait 1 hr for a new build to occur. But rather, if all of my builds are failing, I _must_ bump the version of the package for the package to get updated at the hour marker. I would prefer that r-universe would update and retry failed builds at the hour marker.

**Comment by jeroen** [comment]
You don't need to update the version, that is completely ignored. r-universe will check every hour if the latest commit in the branch it is tracking has changed. If you have pushed new commits, it will trigger a new build.
