### ISSUE TITLE
request to set `_R_CHECK_TESTS_NLINES_=0`

### ISSUE THREAD

**Issue by pawelru** [r-universe-org/help#401]
This would print out all the output lines in case of test failure. Sometimes the stack trace is quite lengthy and just 13 lines of it (a default value) doesn't help much. This diverges from the default a little but I feel there is a value for package maintainers. Alternatively, this could be a very big number (1000?) to avoid some extreme case. I'm interested in hearing your thoughts on this.

**Comment by jeroen** [comment]
Are you aware we already print all the logs underneath the check output in the GHA logs?

<img width="865" alt="Screenshot 2024-04-30 at 18 11 15" src="https://github.com/r-universe-org/help/assets/216319/c25bed28-aad4-4876-a710-5c60f9d913b3">

**Comment by pawelru** [comment]
Yes. This is what I'm referring to. On test failure, rcmdcheck reports only last 13 lines of output. This is not very actionable. An example:
https://github.com/r-universe/pharmaverse/actions/runs/8882670125/job/24388015743
![image](https://github.com/r-universe-org/help/assets/12943682/5f05ad50-e987-4420-b427-c339dcba2eb5)
(highlighted the part telling about 13 lines of output)

**Comment by jeroen** [comment]
I mean underneath the check log, you can expand the full log files:

<img width="865" alt="326893945-c25bed28-aad4-4876-a710-5c60f9d913b3" src="https://github.com/r-universe-org/help/assets/216319/521b189d-d6b5-4e55-b735-51f5b3409396">

**Comment by pawelru** [comment]
Yes. This is what I need. Thanks for pointing this!
