### ISSUE TITLE
Older R version than devel and release

### ISSUE THREAD

**Issue by TanguyBarthelemy** [r-universe-org/help#413]
I would like to allow certain users to access my packages (which are not currently on CRAN) via R-universe.
However, they use different versions of R (4.0, 4.1 or 4.2) and rarely the latest.  

Is it possible to set the versions that will be built and made available on r-universe?

**Comment by jeroen** [comment]
Users can always install the packages, but they have to install from source on platforms for which we don't provide binaries.
We have binaries for the same platforms as CRAN, i.e. for `r-devel` `r-release` and `r-oldrel` on Windows and for `r-release` and `r-oldrel` on MacOS.

**Comment by TanguyBarthelemy** [comment]
Thank you so to install a package with R 4.1 (for example) you'll have to have rtools installed and build the package locally.

**Comment by jeroen** [comment]
Yes indeed on Windows you need the rtools version that matches the version of R. For R-4.1 you need [rtools40](https://cran.r-project.org/bin/windows/Rtools/rtools40.html).

**Comment by TanguyBarthelemy** [comment]
Thank you

**Comment by jeroen** [comment]
But if possible you should encourage your users to update to a recent version of R. It will make their lives much much easier.

**Comment by TanguyBarthelemy** [comment]
Of course! But sometimes in production, they have no choice in keeping their stable version (and versions of packages).

Also this argument doesn't work because on the one hand we are encouraged to update the version of R, packages and tools we use, but on the other hand, for certain technologies (java version for example) we are completely blocked by the structures in place.

CRAN only accepts packages requiring java <= 11 (whereas java 11 was released in September 2018, java 17 in September 2021 and today the stable version of java is 21).

Message from CRAN : "You should be aware that many users are in companies that update very rarely and for example. Hence my suggestion is to make it work with the set of Java versions available on the CRAN machines."

For the r-universe, it was the same thing a few years ago:
https://github.com/r-universe-org/help/issues/185
