### ISSUE TITLE
Possible to disable external universe packages being shown in organisation's universe?

### ISSUE THREAD

**Issue by andrjohns** [r-universe-org/help#423]
For https://stan-dev.r-universe.dev/builds, it lists packages from multiple universes for `cmdstanr`:

![image](https://github.com/r-universe-org/help/assets/27717896/344aa917-9d6d-4eea-a9ae-c64a43dfac65)

Is it possible to disable this, so that the Stan-Dev R-Universe only shows packages from our universe? It feels a bit confusing for end-users that the "official" Stan universe is listing other users/forks

**Comment by jeroen** [comment]
Yes I'm sorry about this, I'm going to fix that asap.

**Comment by jeroen** [comment]
OK I updated the algorithm to no longer cross reference packages from other universes.

**Comment by jeroen** [comment]
Btw, could you include https://github.com/stan-dev/rstan/commit/acc6db4ebe1361dd08b457ade91c5dbbc9672161 in the next CRAN release of StanHeaders? There was a recent CRAN release but it looks like from another branch.

**Comment by andrjohns** [comment]
> Btw, could you include [stan-dev/rstan@acc6db4](https://github.com/stan-dev/rstan/commit/acc6db4ebe1361dd08b457ade91c5dbbc9672161) in the next CRAN release of StanHeaders? There was a recent CRAN release but it looks like another branch.

@bgoodri FYI for `StanHeaders`
