### ISSUE TITLE
On r-universe package websites some url syntax such as `<doi:>` in DESCRIPTION files doesn't render as hyperlinks

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#424]
This is a super minor issue but I thought I'd check if you'd spotted it.

In the `Description:` field of the `DESCRIPTION` file (and I guess in helpfile documentation as well) r-universe doesn't render some R linking syntax as URLs. These are `<doi:>`, `<url:>`, `<arxiv:>`, `<issn:>`, `<isbn:>`, `<ftp:>` - there may be others - apologies I don't know where the official docs are for these.

Here are some examples where they haven't been rendered

* `<doi:>`/`<DOI:>` <https://remlapmot.r-universe.dev/OneSampleMR>

<img width="1121" alt="Screenshot 2024-06-04 at 19 43 50" src="https://github.com/r-universe-org/help/assets/3777473/6ddc2c7e-a216-450d-a5d3-cc207f8728ab">

* `<url:>`/`<URL:>` <https://cran.r-universe.dev/flexsurv/doc/manual.html#ajfit>

* `<arxiv:>`/`<arXiv:>` <https://cran.r-universe.dev/EATME>

* `<issn:>`/`<ISSN:>` <https://cran.r-universe.dev/recapr>

* `<isbn:>`/`<ISBN:>` <https://cran.r-universe.dev/cinterpolate>

* `<ftp:>` <https://cran.r-universe.dev/homologene>

Whereas these do render as hyperlinks on CRAN, e.g. <https://cran.r-project.org/package=OneSampleMR>.

**Comment by jeroen** [comment]
Thanks for the suggestion! I noticed this as well, but I wasn't sure if it is a good idea to inject html code here. 

Also unfortunately R does not expose the code it uses to parse these urls (I think it is done with `htmlify_text` which is inlined inside `tools:::.DESCRIPTION_to_HTML`.

But I think we can do it for some the cases you mention above.

**Comment by jeroen** [comment]
Btw it looks like `arxiv:` is not rendered? https://cran.r-project.org/web/packages/EATME/index.html

**Comment by remlapmot** [comment]
Oh yes - sorry I didn't check all the CRAN pages.

Also there is an unexported `linkify()` function in pkgdown which can handle the doi, arxiv, and I think ftp and http (this function seems to produce a bad URL if there is a space after the `:`).

``` r
pkgdown:::linkify("<arXiv:2203.03384>")
#> [1] "&lt;<a href='https://arxiv.org/abs/2203.03384'>arXiv:2203.03384</a>&gt;"
```

``` r
pkgdown:::linkify("<doi:10.1016/j.jeconom.2015.06.004>")
#> [1] "&lt;<a href='https://doi.org/10.1016/j.jeconom.2015.06.004'>doi:10.1016/j.jeconom.2015.06.004</a>&gt;"
```

<sup>Created on 2024-06-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by jeroen** [comment]
OK I have implemented it for `doi:` and `arxiv:` and `https://` links at least. Do you want to check some packages if it seems to work now? I'm not sure yet if it is worth implementing the others (isbn, ftp, etc).

**Comment by remlapmot** [comment]
Works beautifully - thanks very much.

I agree that those other ones don't seem worth it.
