### ISSUE TITLE
How can I see all the packages when I do a search

### ISSUE THREAD

**Issue by ManuelSpinola** [r-universe-org/help#432]
I did a search using the term "biodiversity", and the result show me the first 50 ("Showing 50 of total 102 results").  How can I see the remaining packages?

**Comment by jeroen** [comment]
I haven't implemented this yet in the webUI. The API supports a `limit` parameter, so you can do:

```r
results <- jsonlite::fromJSON('https://r-universe.dev/api/search?q=biodiversity&limit=1000')
```

**Comment by ManuelSpinola** [comment]
Thank you very much.

**Comment by jeroen** [comment]
The search engine now shows 200 results, and lazy-loads the results cards such that results still load quickly.
