### ISSUE TITLE
Search doesn't seem to be able to find packages that aren't under the org/username of a universe

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#446]
It's such a great strength of the r-universe system that we can include packages from other users/orgs in our own r-universe. But I think I notice that in this case the search doesn't seem to find them.

E.g. in <https://mrcieu.r-universe.dev/> we have MVMR <https://mrcieu.r-universe.dev/MVMR> by one of our reseachers (GitHub username WSpiller) - but search doesn't seem to be able to find it, 2 example searches below.

<https://r-universe.dev/search/?q=universe%3Amrcieu%20MVMR>
![CleanShot 2024-07-09 at 08 36 57@2x](https://github.com/r-universe-org/help/assets/3777473/e7074ac4-5e75-40d1-af62-96d75564f346)

<https://r-universe.dev/search/?q=universe%3Amrcieu%20package%3AMVMR>
![CleanShot 2024-07-09 at 17 01 55@2x](https://github.com/r-universe-org/help/assets/3777473/1fc6e8fe-7f73-4edb-a0c1-8a7c23c6aa39)

I tried a few other packages under different usernames and search also couldn't find them. Or maybe I'm doing something wrong with the searches.

**Comment by jeroen** [comment]
This is expected. Some packages exist in many universes, but for searching we only want to show the "official" home to prevent duplicates.

By default we assume that the package that lives in the universe of the owner is the real one (in your case `WSpiller`), and the other sources are forks/copies.

You fix this by adding the universe URL to the URL field in the upstream package DESCRIPTION file. Hence in this case you would need to add `https://mrcieu.r-universe.dev/MVMR` the URL field in https://github.com/WSpiller/MVMR/blob/master/DESCRIPTION#L15 and then r-universe will treat `https://mrcieu.r-universe.dev` as the true home, and it will get indexed in search.

**Comment by remlapmot** [comment]
Oh sorry, that's clever, thanks for the explanation.
