### ISSUE TITLE
R-universe URLs - Recv failure: Connection was reset

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/help#464]
I'm currently getting the following back from Winbuilder:

Found the following (possibly) invalid URLs:
  URL: https://community.r-multiverse.org/nanonext
    From: README.md
    Status: Error
    Message: Recv failure: Connection was reset
  URL: https://shikokuchuo.r-universe.dev/nanonext
    From: README.md
    Status: Error
    Message: Recv failure: Connection was reset

These are just the links for the readme badges.

Do you have an idea of what this is?

Not super important I can always remove the links for the CRAN submission.

**Comment by jeroen** [comment]
Can you try again? I have been pushing some updates maybe it was just temporary.

**Comment by shikokuchuo** [comment]
Still getting the same...

**Comment by jeroen** [comment]
Ugh, i'll look into it. Can you link to the winbuilder log file?

**Comment by shikokuchuo** [comment]
Thanks! https://win-builder.r-project.org/r6dbYdsHl3E4/

**Comment by jeroen** [comment]
It looks like their winbuilder service currently cannot access any cloudflare resources. It almost looks as if their firewall is blocking cloudflare. Hopefully this is temporary.

**Comment by jeroen** [comment]
I think these problems have disappeared. Uwe said there were indeed firewall problems, but it should be fixed now.
