### ISSUE TITLE
Binary not installed for Ubunutu 22

### ISSUE THREAD

**Issue by JosiahParry** [r-universe-org/help#481]
Discovered in https://github.com/JosiahParry/valve/issues/14

When installing a package from R-universe that has a linux binary, it will not install from the binary but rather from source. 

However, if you point R directly to the binary tar.gz, it will install the binary.

Is this intended?

**Comment by jeroen** [comment]
We only have binaries for ubuntu:latest (24.04) right now. See https://github.com/r-universe-org/help?tab=readme-ov-file#does-r-universe-have-linux-binaries
