### ISSUE TITLE
installation problem with mac binary from bioc.r-universe.dev

### ISSUE THREAD

**Issue by vjcitn** [r-universe-org/help#491]
setup:

> options(repos=c(BioCsoft="https://bioc.r-universe.dev", CRAN="https://cloud.r-project.org"))

> getOption("repos")
                     BioCsoft                          CRAN 
"https://bioc.r-universe.dev" "https://cloud.r-project.org" 

> install.packages("impute")
Installing package into ‘/Users/papa/Library/R/arm64/4.4/library’
(as ‘lib’ is unspecified)
trying URL 'https://bioc.r-universe.dev/bin/macosx/big-sur-arm64/contrib/4.4/impute_1.79.0.tgz'
Content type 'application/x-gzip' length 661436 bytes (645 KB)
==================================================
downloaded 645 KB

The downloaded binary packages are in
	/var/folders/x3/y47x73xn0s3cd4hh22jpl4440000gp/T//RtmpPYveh1/downloaded_packages

> library(impute)
Error: package or namespace load failed for ‘impute’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/papa/Library/R/arm64/4.4/library/impute/libs/impute.so':
  dlopen(/Users/papa/Library/R/arm64/4.4/library/impute/libs/impute.so, 0x0006): Library not loaded: /opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0/libgfortran.5.dylib
  Referenced from: <A86FE63B-0C87-3374-B7F7-CCEBCE31F747> /Users/papa/Library/R/arm64/4.4/library/impute/libs/impute.so
  Reason: tried: '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0/libgfortran.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0/libgfortran.5.dylib' (no such file), '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0/libgfortran.5.dylib' (no such file), '/usr/local/lib/libgfortran.5.dylib' (no such file), '/usr/lib/libgfortran.5.dylib' (no such file, not in dyld cache)

Enter a frame number, or 0 to exit   

1: library(impute)
2: tryCatch({
    attr(package, "LibPath") <- which.lib.loc
    ns <- loadNames
3: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatchOne(expr, names, parentenv, handlers[[1]])
5: value[[3]](cond)

The binary from Bioconductor's BiocManager::install will load.

**Comment by jeroen** [comment]
Duplicate of https://github.com/r-universe-org/help/issues/494, lets continue the discussion over there.
