### ISSUE TITLE
is it expected that search differentiates single and double quotes

### ISSUE THREAD

**Issue by maelle** [r-universe-org/help#504]
https://r-universe.dev/search?q=%22weather%20data%27%27 vs https://r-universe.dev/search?q=%27weather%20data%27

**Comment by jeroen** [comment]
I think only double quotes work (judging from the number of reported results) but you can dive into the mongo text search spec to find out: https://www.mongodb.com/docs/manual/core/indexes/index-types/index-text/#std-label-index-type-text

**Comment by maelle** [comment]
I'll add this to the docs!
