### ISSUE TITLE
codeberg.org is not recognized as a Git server

### ISSUE THREAD

**Issue by bastistician** [r-universe-org/help#507]
An example is package ['hhh4contacts'](http://cran.dev/hhh4contacts), where the "On CRAN" tooltip in the frontend wrongly claims

> A package 'hhh4contacts' exists on CRAN but description does not link to any git repository or issue tracker

The [docs](https://docs.r-universe.dev/publish/set-up.html#how-much-github-is-compulsory) say that packages

> may be hosted on any public Git server.

but it seems `cranscraper:::find_git_url()` [only knows about GitHub/GitLab/Bitbucket](https://github.com/r-universe-org/cranscraper/blob/dcdf1f5a577921a6f261b29b823443e7b2a5e3ed/R/cran.R#L30).

**Comment by jeroen** [comment]
The documentation refers to the fact that we can pull source code from any git server, by specifying the git source manually in the [packages.json](https://github.com/EE-lib/ee-lib.r-universe.dev/blob/HEAD/packages.json) in [https://ee-lib.r-universe.dev](https://ee-lib.r-universe.dev) indeed.

However there is no easy way to infer if a git server also has an issue tracker. But if you want we can add codeberg.org to the list of known git servers with issue trackers, that can also be picked up by our scrapers...

**Comment by bastistician** [comment]
I see. Then maybe the text in the tooltip for `https://github.com/cran/` URLs should be replaced by:

> A package '${package}' exists on CRAN but its description does not link to a known Git server or issue tracker

?

According to `grep("codeberg", tools::CRAN_package_db()$BugReports, value = TRUE)`, at least I am not the only one experimenting with codeberg.org. ;)

**Comment by jeroen** [comment]
OK the scraper has now [picked up](https://github.com/r-universe-org/cran-to-git/commit/fe24fa5b7004d513853f01fba2096245b1bd8c51) on these codeberg repositories. 


Future not for myself: there are currently 3 places where we look for known git providers:
 - cranscraper: https://github.com/r-universe-org/cranscraper/commit/22bac18241a9eb0ea77de12d1e9236b04c773633
 - buildtools: https://github.com/r-universe-org/build-source/commit/2039cc0a1eb9d42d5c1ebae9b07d6f195de9c0a6
 - cranstatus api: https://github.com/r-universe-org/cranlike-server/commit/db509f24856bba597ab47c0e12d542ff87412a4f
 
 Maybe this needs refactoring.
