### ISSUE TITLE
R-release trying to obtain next version (3.20) of Bioconductor packages

### ISSUE THREAD

**Issue by remlapmot** [r-universe-org/help#516]
We have a package which has Bioconductor dependencies https://mrcieu.r-universe.dev/genepi.utils

Today we see some build failures related to those dependencies.

A little bit surprisingly to me the Bioconductor URLs contain 3.20, whereas I thought the current release is 3.19.

My knowledge about Bioconductor isn't very good.

I can't tell if there's a minor misconfiguration in the r-universe system, or whether this is normal (and say the Bioconductor server is down/slow to respond).

Here's a link to the builds:

https://github.com/r-universe/mrcieu/actions/runs/11498107650

https://github.com/r-universe/mrcieu/actions/runs/11498107650/job/32011911539

(Sorry for the noise if this is just my lack of understanding of Bioconductor.)

**Comment by roaldarbol** [comment]
I think [this is happening for me too](https://github.com/r-universe/roaldarbol/actions/runs/11596168499/job/32286834211) (but I've only just added a Bioconductor package, so I don't know if it *should* be working). @remlapmot I can see that your package subsequently successfully built, did you do anything particular to resolve it?

I used a [suggested solution](https://github.com/r-lib/devtools/issues/700#issuecomment-235127291) for using BioConductor packages in package development, but maybe there's a better way of doing that? For reference, I'm using the `{rhdf5}` package from BioConductor.

**Comment by jeroen** [comment]
@roaldarbol Looking at the log files, I think your error may just be an intermittent failure, probably because upstream bioconductor is today in the process of deploying the 3.20 release. You can try to click the 🔄 icon on https://roaldarbol.r-universe.dev/builds ?

**Comment by roaldarbol** [comment]
Just gave it a another try, but still fails. I do think you might be right though, I'll try again tomorrow. 
One thing I did notice (and I don't know if it's at all relevant) is that the package name when installing is `Rhdf5lib`, not `rhdf5`. But maybe that's expected?

**Comment by jeroen** [comment]
That is a different package: https://bioconductor.org/packages/release/bioc/html/Rhdf5lib.html

**Comment by roaldarbol** [comment]
Ah, alright. Could it be because it’s still the development version on BioC 3.20 and release on  BioC 3.19?

**Comment by jeroen** [comment]
BioC 3.20 is released today so perhaps some mirror is out of sync. Let's give it a few hours.

**Comment by jeroen** [comment]
I switched to another bioc mirror, all should be good now.

**Comment by roaldarbol** [comment]
Works, thanks!
