### ISSUE TITLE
Code Signing Error when loading the binary package on MacOS

### ISSUE THREAD

**Issue by akhst7** [r-universe-org/help#518]
Hi ,

I run into the Apple's code signing error when loading BPCells_0.2.0.(r-4.4-arm64)

library(BPCells)
Error: package or namespace load failed for ‘BPCells’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so':
  dlopen(/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so, 0x0006): tried: '/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so' (code signature in <294A657F-219D-3EB2-AFE6-6CC754DEF5D2> '/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so' (no such file), '/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so' (code signature in <294A657F-219D-3EB2-AFE6-6CC754DEF5D2> '/Volumes/Document/4.3.X_Rlib/BPCells/libs/BPCells.so' not valid for use in process: library load disallowed by system policy)

![Screenshot 2024-11-01 at 11 19 06 AM](https://github.com/user-attachments/assets/05886fd4-95c2-452c-9a5d-6daf4c86c7ee)

I appreciate if you can fix this.

Thanks.

**Comment by jeroen** [comment]
It is not possible to sign individual R packages. If you use the official [R for MacOS](https://cran.r-project.org/bin/macosx/) and use `install.packages()` in R to download and install the package then it works.

You typically only get this message if you downloaded the file in a browser.

Where did you install R from? How did you download and install the package?

**Comment by akhst7** [comment]
Got it. 

Thanks.
