### ISSUE TITLE
Update cranlibs

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#553]
See need to sync https://github.com/r-universe-org/cranlibs with https://mac.r-project.org/bin/darwin20/.

See discussion on https://github.com/r-universe/janmarvin/commit/d333716d99ab0815ffe3cfdb1af3b8fa9e5892ce

**Comment by jeroen** [comment]
@janmarvin I think this should be fixed now.

**Comment by JanMarvin** [comment]
Perfect, thank you!
