### ISSUE TITLE
Store Linux binaries in package server

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#7]
Just like rspm, but only for ubuntu 20.04.

**Comment by jeroen** [comment]
We have this, but only for `ubuntu:latest` (which is ubuntu 22.04 right now).

**Comment by gorkang** [comment]
This is fantastic. Thanks a lot @jeroen !

**Comment by jeroen** [comment]
Updated the answer a bit, thanks for reviving this issue :)

**Comment by eitsupi** [comment]
> We mostly do this for ourselves, such that we get quick installations of dependencies on our own build environment, but you can use the binaries as well. It works slightly different then rsudio's thing: you need to add the repo with binaries to your repos `https://{{universe}}/bin/linux/{{distro}}/{{r-version}}/`, for example:

Do you plan to display this in the UI or somewhere?
I use this personally (eitsupi/prqlr#7), but I don't think many users realize it.

**Comment by gorkang** [comment]
> I wasn't sure people would care about it much, because it is currently limited to `ubuntu:latest` and `r:release`. But we could display it somewhere...

Not sure how many "of us" there are, but we do care about this :) 

It would be great if this was well documented. After using the Rstudio Package Manager, it is kind of hard moving away from binaries.

**Comment by jeroen** [comment]
OK I have added a link to the linux binary on the package homepage, and also a link with few words of caution to the faq:

![Screen Shot 2022-12-09 at 3 31 58 PM](https://user-images.githubusercontent.com/216319/206725222-b6c2a9c2-fbcc-4f53-8dd9-18a8ccbc4545.png)

**Comment by eitsupi** [comment]
That looks wonderful!
Thanks!
