### ISSUE TITLE
Extra rebuilds for new/missing packages

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/help#85]
Also trigger rebuilds for packages that are not on the package server yet. This happens e.g. when the build failed due to a missing dependency.

**Comment by shikokuchuo** [comment]
Hi Jeroen, are you currently testing this? FYI - I had a working build up and it reverted back to showing an earlier build that failed (I think internet issues on the build machine at the time). shikokuchuo/ichimoku

**Comment by jeroen** [comment]
All packages that exist on the package server automatically get rebuilt once per month. The new feature is for packages that are not on the package server yet.

**Comment by shikokuchuo** [comment]
OK, thanks. You might want to check out a potential (related?) issue. Basically I had the Windows builds fail after a commit yesterday, I pushed another version later on, and it built fine. Then the system switched back to showing the earlier version. The binaries got rebuilt for that version, but it is now stuck on the previous version. The latest build is there in the github repo, but querying R-universe API it is not there any more. repo: shikokuchuo/ichimoku

**Comment by jeroen** [comment]
Hmmm it looks to be there? https://shikokuchuo.r-universe.dev/ui#builds

**Comment by shikokuchuo** [comment]
There is a later build 0.3.51.2. You can see the successful run at: https://github.com/r-universe/shikokuchuo/actions/workflows/build.yml

**Comment by jeroen** [comment]
Ah okay, I think I had manually re-triggered an old run, so maybe that has overwritten the newer binaries.
I'll retrigger the run you link above now :-)
I hope to implement something that people can retrigger runs themselves soon.

**Comment by shikokuchuo** [comment]
Ah sure, that makes sense. I am sure a newer push would have sorted it out in any case, but just wanted to alert you in case there was a bug in the system. Thanks!

**Comment by jeroen** [comment]
There is an experimental API and UI now for triggering rebuilds. For failed builds, you can click the circular arrow on a package table e.g https://r-lib.r-universe.dev
